# Generated by Django 5.0.6 on 2024-09-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_message_image_message_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
